
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Manuel Cañamaque
 */
public class VentanaJuego extends javax.swing.JFrame {
    
    
    //Juego juego = new Juego();
    
    /**
     * Creates new form VentanaJuego
          */
    public VentanaJuego() {
        initComponents();        
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        
        //Cambiamos el color de los JLabel segun el que haya seleccionado el usuario
        label_Nombre.setText(Juego.getNombre()+" vs Ordenador");
        label_Nombre.setForeground(Juego.getColor());
        label_Recuento.setForeground(Juego.getColor());
        label_Resultado.setForeground(Juego.getColor());
        
        //Ocultamos los botones de Lagarto y Spock si este modo no ha sido seleccionado.
        if(Juego.getEstiloJuego()==0){
            boton_Lagarto.setVisible(false);
            boton_Spock.setVisible(false);
        }
        boton_Jugar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Nombre = new javax.swing.JLabel();
        label_Recuento = new javax.swing.JLabel();
        label_Resultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_Piedra = new javax.swing.JButton();
        boton_Papel = new javax.swing.JButton();
        boton_Tijera = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boton_Lagarto = new javax.swing.JButton();
        boton_Spock = new javax.swing.JButton();
        label_Manos = new javax.swing.JLabel();
        boton_Jugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_Reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label_Nombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Nombre.setText("Jugador 1 vs Ordenador");
        label_Nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Nombre.setPreferredSize(new java.awt.Dimension(529, 29));

        label_Recuento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_Recuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Recuento.setText("0 a 0");
        label_Recuento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Recuento.setPreferredSize(new java.awt.Dimension(529, 29));

        label_Resultado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Resultado.setPreferredSize(new java.awt.Dimension(529, 29));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        boton_Piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/piedra.png"))); // NOI18N
        boton_Piedra.setToolTipText("Piedra");
        boton_Piedra.setBorder(null);
        boton_Piedra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton_Piedra.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        boton_Piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PiedraActionPerformed(evt);
            }
        });

        boton_Papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/papel.png"))); // NOI18N
        boton_Papel.setToolTipText("Papel");
        boton_Papel.setBorder(null);
        boton_Papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_PapelActionPerformed(evt);
            }
        });

        boton_Tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tijera.png"))); // NOI18N
        boton_Tijera.setToolTipText("Tijera");
        boton_Tijera.setBorder(null);
        boton_Tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_TijeraActionPerformed(evt);
            }
        });

        boton_Lagarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lagarto.png"))); // NOI18N
        boton_Lagarto.setToolTipText("Lagarto");
        boton_Lagarto.setBorder(null);
        boton_Lagarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_LagartoActionPerformed(evt);
            }
        });

        boton_Spock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spock.png"))); // NOI18N
        boton_Spock.setToolTipText("Spock");
        boton_Spock.setBorder(null);
        boton_Spock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_SpockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(boton_Lagarto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_Spock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boton_Spock)
                    .addComponent(boton_Lagarto))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_Piedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_Papel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_Tijera, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_Tijera)
                    .addComponent(boton_Papel)
                    .addComponent(boton_Piedra))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label_Manos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label_Manos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Manos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_Manos.setPreferredSize(new java.awt.Dimension(529, 29));

        boton_Jugar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        boton_Jugar.setText("Jugar");
        boton_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_JugarActionPerformed(evt);
            }
        });

        jLabel1.setText("*Seleccione su mano y presione jugar.");

        boton_Reiniciar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        boton_Reiniciar.setText("Reiniciar");
        boton_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_Jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_Reiniciar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Recuento, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Manos, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Recuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Manos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Jugar)
                    .addComponent(boton_Reiniciar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_PiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PiedraActionPerformed
        Juego.setMovimientoJugador(Juego.PIEDRA);        
        boton_Jugar.setEnabled(true);
    }//GEN-LAST:event_boton_PiedraActionPerformed

    private void boton_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_JugarActionPerformed
        label_Resultado.setText(Juego.compararJugadas());        
        label_Recuento.setText(Juego.getPartidasGanadas()+" a "+Juego.getPartidasPerdidas());
        label_Manos.setText(Juego.getMovimientoJugadorToString()+" vs "+ Juego.getMovimientoMaquinaToString());
        boton_Jugar.setEnabled(false);
        
        //Si se ha acabado el juego, mostramos un JOptionPane con las posibles opciones.
        if(Juego.finJuego()){
            JOptionPane.showMessageDialog(this, "Ganador: "+Juego.ganadorToString());
            int seleccion = JOptionPane.showOptionDialog( this,"¿Qué desea hacer a continuación?",
            "Fin del juego",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,
            null, new Object[] { "Jugar de nuevo", "Cambiar opciones", "Salir" },"Jugar de nuevo");
            switch(seleccion){
                case 0:
                    Juego.reiniciarJuego();
                    label_Resultado.setText("");        
                    label_Recuento.setText(Juego.getPartidasGanadas()+" a "+Juego.getPartidasPerdidas());
                    label_Manos.setText("");
                    boton_Jugar.setEnabled(false);
                    break;
                case 1:
                    Juego.reiniciarJuego();
                    this.setVisible(false);
                    MenuInicio menu = new MenuInicio();
                    menu.setVisible(true);
                    break;                    
                case 2:
                default:
                    System.exit(0);
                    break;
            }  
        }        
    }//GEN-LAST:event_boton_JugarActionPerformed

    private void boton_PapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_PapelActionPerformed
        Juego.setMovimientoJugador(Juego.PAPEL);
        boton_Jugar.setEnabled(true);
    }//GEN-LAST:event_boton_PapelActionPerformed

    private void boton_TijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_TijeraActionPerformed
        Juego.setMovimientoJugador(Juego.TIJERA);
        boton_Jugar.setEnabled(true);
    }//GEN-LAST:event_boton_TijeraActionPerformed

    private void boton_LagartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_LagartoActionPerformed
        Juego.setMovimientoJugador(Juego.LAGARTO);
        boton_Jugar.setEnabled(true);
    }//GEN-LAST:event_boton_LagartoActionPerformed

    private void boton_SpockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_SpockActionPerformed
        Juego.setMovimientoJugador(Juego.SPOCK);
        boton_Jugar.setEnabled(true);
    }//GEN-LAST:event_boton_SpockActionPerformed

    private void boton_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ReiniciarActionPerformed
        //Usamo el metodo para reiniciar el juego y limpiamos los campos.
        Juego.reiniciarJuego();
        label_Resultado.setText("");        
        label_Recuento.setText(Juego.getPartidasGanadas()+" a "+Juego.getPartidasPerdidas());
        label_Manos.setText("");
        boton_Jugar.setEnabled(false);
    }//GEN-LAST:event_boton_ReiniciarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Mostramos un JOptionPane al intentar cerrar la ventana
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de que desea cerrar el juego?",
                "Cerrar Juego", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);            
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Jugar;
    private javax.swing.JButton boton_Lagarto;
    private javax.swing.JButton boton_Papel;
    private javax.swing.JButton boton_Piedra;
    private javax.swing.JButton boton_Reiniciar;
    private javax.swing.JButton boton_Spock;
    private javax.swing.JButton boton_Tijera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Manos;
    private javax.swing.JLabel label_Nombre;
    private javax.swing.JLabel label_Recuento;
    private javax.swing.JLabel label_Resultado;
    // End of variables declaration//GEN-END:variables
}
